name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 1. Извлечение кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      # 4. Запуск Codex Review
      - name: Run Codex Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/codex_review.py
